CrowdStrike/ember-toucan-core

docs/components/button/index.md

I noticed the buttons on mobile started to get cutoff due to being horizontal.  Instead, I think it makes sense to stack them vertically when on mobile like other design systems.
---
**CI**
CI (Actions) should all be green 🟢 
**Docs App**
- View the docs app via the Preview URL
- Make your browser width small (or view on your mobile device!)
- Verify the buttons don't butt up against one another, but instead are vertical
---

docs: Stack buttons on mobile

---

.github/workflows/ci.yml

Related to https://github.com/CrowdStrike/ember-headless-form/pull/55 / https://github.com/CrowdStrike/ember-headless-form/issues/54, we're hitting the same issue here.

fix: Skip canary tests for now

---

docs-app/.prettierrc.js
docs-app/app/templates/application.hbs
docs-app/app/templates/index.hbs
docs-app/package.json
ember-toucan-core/.prettierrc.cjs
ember-toucan-core/package.json
ember-toucan-core/src/components/form/-private/error.hbs
pnpm-lock.yaml

This PR adds `prettier-plugin-tailwindcss` to the docs-app + `ember-toucan-core` package.
Closes #41 
---
- https://tailwindcss.com/blog/automatic-class-sorting-with-prettier
---
- Non-visual change, only code formatting so builds need to be green.
---
N/A

#41: Add Tailwind prettier plugin+run it

---

docs-app/.ember-cli
test-app/.ember-cli

Set specific ports for the docs and test apps so you can run them both at the same time.
---
- https://guides.emberjs.com/release/configuring-ember/configuring-ember-cli/
---
If you want to manually check:
```
cd test-app
pnpm i
pnpm start
cd docs-app
pnpm i
pnpm start
```
---
N/A

feat: Use different ports for test/docs apps

---

docs/components/textarea/index.md
ember-toucan-core/src/components/form/controls/textarea.hbs
ember-toucan-core/src/components/form/controls/textarea.ts
ember-toucan-core/src/components/form/textarea-field.hbs
ember-toucan-core/src/components/form/textarea-field.ts
test-app/tests/integration/components/textarea-field-test.gts
test-app/tests/integration/components/textarea-test.gts

Adds the error box-shadow to the `<textarea>` element and wires it up with `<TextField>`.
I noticed this when building the Checkbox component(s) and thought it'd be good to fix now before I forget.
Closes #51
---
- Visit https://dc969626.ember-toucan-core.pages.dev/docs/components/textarea-field
- Scroll down and verify the error shadow is present on the text areas with an error
---

#51: Add shadow-error-outline to Textarea

---

docs/components/checkbox-field/demo/base-demo.md
docs/components/checkbox-field/index.md
docs/components/checkbox/demo/base-demo.md
docs/components/checkbox/index.md
ember-toucan-core/package.json
ember-toucan-core/src/components/form/checkbox-field.hbs
ember-toucan-core/src/components/form/checkbox-field.ts
ember-toucan-core/src/components/form/controls/checkbox.hbs
ember-toucan-core/src/components/form/controls/checkbox.ts
ember-toucan-core/src/template-registry.ts
ember-toucan-core/unpublished-development-types/index.d.ts
test-app/tests/integration/components/checkbox-field-test.gts
test-app/tests/integration/components/checkbox-test.gts

This PR introduces a `Checkbox` control component and `CheckboxField` component. 
**NOTE:** These components are not 100% styled yet, as we are still figuring out where to land on a few things. This is about ~75% close though.
Closes #48 
---
- These are only presentational components, so test should pass
- View the checkbox link at https://48034b83.ember-toucan-core.pages.dev/docs/components/checkbox and review the documentation
- **NOTE:** This checkbox does not toggle on click! It is presentational only
- View the link at https://48034b83.ember-toucan-core.pages.dev/docs/components/checkbox-field  and review the documentation
- **NOTE:** These components are not 100% styled yet, as we are still figuring out where to land on a few things.  This is about ~75% close though.
---
**UI …

#48: Add Checkbox component

---

.github/workflows/ci.yml

Skip adding the api-docs in the GitHub comment as we aren't publishing them (yet).
---
- Verify the bot below doesn't post an api-docs link
---
N/A

docs: Don't add api-docs url for now

---

docs/components/fieldset/demo/base-demo.md
docs/components/fieldset/index.md
ember-toucan-core/package.json
ember-toucan-core/src/components/form/fieldset.hbs
ember-toucan-core/src/components/form/fieldset.ts
ember-toucan-core/src/template-registry.ts
test-app/tests/integration/components/fieldset-test.gts

This PR introduces a `Fieldset` component so we can build checkbox and radio groups.
**NOTE:** These components are not 100% styled yet, as we are still figuring out where to land on a few things. This is about ~75% close though.
Closes #59 
---
- Visit https://bf1e003c.ember-toucan-core.pages.dev/docs/components/fieldset
---
Show how the screenreader picks up on the hint + error text
https://user-images.githubusercontent.com/8069555/222753233-26062d3b-de61-4e74-9671-507619d54204.mov

#59: Add Fieldset component

---

docs/components/field/demo/base-demo.md
docs/components/field/index.md
ember-toucan-core/src/-private/components/control.hbs
ember-toucan-core/src/-private/components/error.hbs
ember-toucan-core/src/components/form/checkbox-field.hbs
ember-toucan-core/src/components/form/fieldset.hbs
ember-toucan-core/src/components/form/input-field.hbs
ember-toucan-core/src/components/form/textarea-field.hbs

This implements the styling changes after a design review.
---
- View https://35eff113.ember-toucan-core.pages.dev/docs/components/textarea-field
- The hint block + control + error block should all have 0.125rem/2px spacing _above_ the elements
- View https://35eff113.ember-toucan-core.pages.dev/docs/components/checkbox-field
- The hint block + error block should have 0.125rem/2px spacing _above_ the elements
- View https://7bfeb461.ember-toucan-core.pages.dev/docs/components/input-field
---

Implement design suggested spacing of elements

---

ember-toucan-core/src/components/form/input-field.hbs
ember-toucan-core/src/components/form/input-field.ts
test-app/tests/integration/components/input-field-test.gts

Fix a styling issue with `input field` that I noticed when doing https://github.com/CrowdStrike/ember-toucan-core/pull/65/files.
Downstream of https://github.com/CrowdStrike/ember-toucan-core/pull/63
| Before  | After |
| <img width="315" alt="Screenshot 2023-03-06 at 3 00 37 PM" src="https://user-images.githubusercontent.com/8069555/223217754-41cb04ae-1f1b-4d05-923a-e6c5b9607e74.png">  | <img width="324" alt="Screenshot 2023-03-06 at 2 56 37 PM" src="https://user-images.githubusercontent.com/8069555/223217656-713b83b0-6c04-4954-9554-9b2a950a1acb.png">  |
| No error border  | With error border  |
---
- View https://e963e8f6.ember-toucan-core.pages.dev/docs/components/input-field#inputfield-with-label-and-error
- Verify error shadow on errored input

fix: Update input-field to use hasError and apply the error shadow

---

ember-toucan-core/src/components/button.ts
ember-toucan-core/src/components/form/checkbox-field.ts
ember-toucan-core/src/components/form/controls/checkbox.ts
ember-toucan-core/src/components/form/controls/input.ts
ember-toucan-core/src/components/form/controls/radio.ts
ember-toucan-core/src/components/form/controls/textarea.ts
ember-toucan-core/src/components/form/field.ts
ember-toucan-core/src/components/form/fieldset.ts
ember-toucan-core/src/components/form/input-field.ts
ember-toucan-core/src/components/form/radio-field.ts
ember-toucan-core/src/components/form/radio-group-field.ts
ember-toucan-core/src/components/form/textarea-field.ts

Adds JSDoc comments for component arguments
Closes #73 
---
- Green build!
- You _could_ pull the repo down and ensure you get VSCode hints as seen below in the image, but not necessary
---
N/A - Developer Experience improvement only, so no visual changes, but in VSCode you should get these helpful hints!

feat: Add JSDoc comments for component args

---

ember-toucan-core/src/components/form/radio-group-field.hbs
test-app/tests/integration/components/radio-group-field-test.gts

For accessibility and after reading through https://adrianroselli.com/2022/02/support-for-marking-radio-buttons-required-invalid.html#R6 again, it seems like this is valid and helps Voice Over announcing the error state.
---
- Tests should pass!
---
N/A - no visual changes

fix: Add aria-invalid + role="radiogroup" to RadioGroupField

---

docs-app/package.json
ember-toucan-core/package.json
ember-toucan-core/src/components/form/controls/input.hbs
ember-toucan-core/src/components/form/controls/textarea.hbs
pnpm-lock.yaml
test-app/package.json
test-app/tests/integration/components/input-field-test.gts
test-app/tests/integration/components/input-test.gts
test-app/tests/integration/components/textarea-field-test.gts
test-app/tests/integration/components/textarea-test.gts

This PR consumes the new changes from `tailwind-toucan-base` and `ember-toucan-styles` so that we can use our new error+focus shadow:
- https://github.com/CrowdStrike/tailwind-toucan-base/releases/tag/v3.4.0
- https://github.com/CrowdStrike/ember-toucan-styles/releases/tag/%40crowdstrike%2Fember-toucan-styles%402.0.1
---
- Visit https://2f323160.ember-toucan-core.pages.dev/docs/components/textarea-field
- Start typing "textarea" into the field and verify you see the focus+error shadow
- Upon completing typing "textarea", the error shadow should be removed and only the focus shadow remains
- Deleting a single character should re-add the focus+error shadow
- Visit https://2f323160.ember-toucan-core.pages.dev/docs/components/input-field#inputfield-with-label-and-error
- Click into input …

feat: Use new shadow-error-focus-outline

---

docs/components/checkbox-field/index.md
docs/components/field/demo/base-demo.md
docs/components/field/index.md
docs/components/fieldset/index.md
docs/components/input-field/index.md
docs/components/radio-group-field/index.md
docs/components/textarea-field/index.md
ember-toucan-core/src/-private/components/error.hbs
ember-toucan-core/src/-private/components/error.ts
ember-toucan-core/src/-private/types.ts
ember-toucan-core/src/components/form/checkbox-field.hbs
ember-toucan-core/src/components/form/checkbox-field.ts
ember-toucan-core/src/components/form/fieldset.hbs
ember-toucan-core/src/components/form/fieldset.ts
ember-toucan-core/src/components/form/input-field.hbs
ember-toucan-core/src/components/form/input-field.ts
ember-toucan-core/src/components/form/radio-group-field.ts
ember-toucan-core/src/components/form/textarea-field.hbs
ember-toucan-core/src/components/form/textarea-field.ts
test-app/app/templates/application.hbs
test-app/tests/integration/components/field-test.gts
test-app/tests/integration/components/fieldset-test.gts

This PR allows for having either a single string for an error or an array of errors.  This will allow us to play more nicely with `ember-headless-form`.
Closes #44 
---
- View https://aa13bb8f.ember-toucan-core.pages.dev/docs/components/field#yielded-items and review the `Yielded Items` > `Error` section for validity
- Verify can render both a single error and multiple errors by clicking the link and scroll down a bit (should be the last example). Please also verify the "Error" section of each page
- https://aa13bb8f.ember-toucan-core.pages.dev/docs/components/fieldset#all-ui-states
- https://aa13bb8f.ember-toucan-core.pages.dev/docs/components/checkbox-field#all-ui-states
- https://aa13bb8f.ember-toucan-core.pages.dev/docs/components/textarea-field#all-ui-states
- …

feat(#44): Add ability to render multiple errors

---

.github/actions/pnpm/action.yml

This PR pins the version of `pnpm` to 7.30.0.  With 7.30.1 we are getting test issues as mentioned over on https://github.com/embroider-build/embroider/issues/1378.  This is causing `main` to fail and all open PRs to also fail.
I filed https://github.com/CrowdStrike/ember-toucan-core/issues/99 so we don't forget.
---
- Green build!
---
N/A

Pin pnpm version to 7.30.0 for now

---

ember-toucan-core/src/components/form/controls/radio.hbs

⚠️ Build is failing currently, but I'm chatting about it in the Ember discord and have an issue filed with embroider. ⚠️
This PR adjusts the radio focus-visible style to match the designs and what was discussed yesterday.
---
This is a visual test and would benefit from something like Percy to see the difference between what is in `main` today versus this PR.  For now you can compare with `main` at https://ember-toucan-core.pages.dev/docs/components/radio-group-field.
- View https://1ce8b4aa.ember-toucan-core.pages.dev/docs/components/radio-group-field
- Click radio options and verify no focus state is applied
- Use the keyboard and TAB into the radio, verify the new focus-visible state is applied
- Use the arrow keys (left + right) to toggle between radio options and verify the …

feat: Adjust radio styling based on designs

---

docs/components/checkbox-group-field/demo/base-demo.md
ember-toucan-core/src/components/form/controls/checkbox.hbs

This PR adjusts the checkbox focus-visible style to match the designs and what was discussed yesterday.  This matches what was done at https://github.com/CrowdStrike/ember-toucan-core/pull/93.
---
This is a visual test and would benefit from something like Percy to see the difference between what is in `main` today versus this PR.  For now you can compare with `main` at https://ember-toucan-core.pages.dev/docs/components/checkbox-group-field.
- View https://d137f197.ember-toucan-core.pages.dev/docs/components/checkbox-group-field
- Click checkbox options and verify no focus state is applied
- Use the keyboard and TAB into the checkbox, verify the new focus-visible state is applied
- Use the TAB to toggle between checkbox options and verify the focus-visible state changes to the …

feat: Adjust checkbox styling based on designs

---

.github/pull_request_template.md

This PR adds a standardized pull request template so that we can prompt external users (non-CS folks) on what we expect when reviewing PRs.  It may also save some of us time writing up PR descriptions!  Feel free to offer any suggestions.
I followed https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository to make this.
---
There is no way to test this until it merges!
---
N/A

docs: Add PR Template

---

ember-toucan-core/src/components/form/checkbox-field.hbs
test-app/tests/integration/components/checkbox-field-test.gts

This applies some design feedback from yesterday.
>  in ember toucan core docs is different spacing between the input group:checkboxes and input group: radio buttons. Checkboxes feel more aired out and radio buttons feel more condensed.
The reason this was happening is because we have built-in padding to the checkbox-field component.  This is to account for the error shadow outline.  We can remove that when in a checkbox-group-field by checking if we are rendered in one via the `@option` argument.
---
- Visit https://fd9c9fbe.ember-toucan-core.pages.dev/docs/components/checkbox-group-field and verify the spacing is now flush-left
- Compare to https://fd9c9fbe.ember-toucan-core.pages.dev/docs/components/radio-group-field and you should not see any shifting in layout between the two (see …

feat: Remove padding when in a checkbox group

---

.github/actions/pnpm/action.yml

pnpm v7.30.3 has been merged and our issue is closed! https://github.com/pnpm/pnpm/releases/tag/v7.30.3 (https://github.com/pnpm/pnpm/issues/6271)
Confirmed the action is now using 7.30.3! https://github.com/CrowdStrike/ember-toucan-core/actions/runs/4516067783/jobs/7954046644?pr=101#step:3:28
Closes #99 
---
- Green build
---
N/A

#99: Revert pnpm version pinning to use latest again after 7.30.3 fixes our issue

---

ember-toucan-core/src/-private/components/error.hbs

This PR updates the existing error icon to match the designs.
---
- Visit https://633cb774.ember-toucan-core.pages.dev/docs/components/textarea-field#all-ui-states
- Verify the alert triangle is used over the alert circle
---
| BEFORE  | AFTER |
| <img width="201" alt="Screenshot 2023-03-27 at 10 36 26 AM" src="https://user-images.githubusercontent.com/8069555/227972817-d758a87c-7c8d-440e-bed4-a0bf324b092f.png">  | <img width="208" alt="Screenshot 2023-03-27 at 9 30 54 AM" src="https://user-images.githubusercontent.com/8069555/227952538-be32f26d-7829-4c64-8b7b-d83db36f5f16.png"> |
| Circle  | Triangle  |

fix: Update error icon to triangle over circle

---

docs/components/file-input-field/index.md
ember-toucan-core/src/components/form/controls/file-input.ts
ember-toucan-core/src/components/form/file-input-field.hbs
ember-toucan-core/src/components/form/file-input-field.ts

The multiple helper in FileInputField already exists in controls/file-input.
Deleting this and passing along the @multiple arg works and is simpler.
Fixes: https://github.com/CrowdStrike/ember-toucan-core/issues/91

fix: FileInputField, remove multiple helper

---

docs/components/file-input-field/demo/base-demo.md
ember-toucan-core/src/components/form/file-input-field.hbs
ember-toucan-core/src/components/form/file-input/delete-button.hbs
ember-toucan-core/src/components/form/file-input/list-item.hbs
ember-toucan-core/src/components/form/file-input/list-item.ts
ember-toucan-core/src/components/form/file-input/list.hbs
test-app/tests/integration/components/file-input-field-test.gts

Note: this does not change the existing markup of the file input field, that will be done in followup work.

style: FileInputField, list, add styles

---

.changeset/gold-steaks-try.md
packages/ember-toucan-core/src/components/button.ts
test-app/tests/integration/components/button-test.gts

This is adding an internal/private only(!) argument `@isButtonGroup` to `<Button>` to allow them being rendered as part of a `<ButtonGroup>` with the proper styling (rounded borders only on the outside parts). This is basically replacing some custom CSS we had previously in place to override the Tailwind-based default styling. Now the `<Button>` component "owns" all of its styling concerns, without other parts poking into its styling implementation from the outside. 
This does not feature any documentation updates, as it is _not_ supposed to be used by anything but `<ButtonGroup>` internally.
---
We cannot really show the changes live, as the other part of the changes is in `@crowdstrike/ui` as part of another PR. The change here would be more obvious had we `<ButtonGroup>` already …

Support `@isButtonGroup` mode for `<Button>`

---

packages/ember-toucan-core/src/components/form/fields/file-input.ts

Adding missing JSDoc for the FileInput.
Related PR comment: https://github.com/CrowdStrike/ember-toucan-core/pull/110#discussion_r1159165826
N / A
---
Probably looks better in VS Code.

docs: FileInput, add jsdoc

---

.changeset/pre.json

This is the result of running `changeset pre exit`, to switch to doing regular `latest` 0.1.x releases instead of `0.1.0-beta.x` releases, see https://github.com/CrowdStrike/ember-toucan-core/pull/127#discussion_r1163227412

changeset: exit prerelease mode

---

docs/toucan-form/changeset-validation/demo/base-demo.md
docs/toucan-form/native-validation/demo/base-demo.md
packages/ember-toucan-core/src/components/form/fields/input.ts
packages/ember-toucan-form/src/-private/input-field.hbs
packages/ember-toucan-form/src/-private/input-field.ts
packages/ember-toucan-form/src/-private/textarea-field.ts
packages/ember-toucan-form/src/components/toucan-form.hbs
packages/ember-toucan-form/src/components/toucan-form.ts
test-app/tests/integration/components/toucan-form/toucan-form-test.gts

This PR builds on top of https://github.com/CrowdStrike/ember-toucan-core/pull/129/files, by adding `Input` support to `ToucanForm`.
Follow up work after this PR merges:
- Cut a release so we can get some feedback
- Add Checkbox support
- Add CheckboxGroup support
- Add RadioGroup support
- Add FileInput support
- Add named-block support to all of above
- Convert to using the `<template>` tag
Usage is:
```hbs template
<ToucanForm
class='space-y-4'
@data={{this.data}}
@onSubmit={{this.handleSubmit}}
as |form|
>
<form.Input @label='First name' @name='firstName' required />
<form.Input @label='Last name' @name='lastName' required />
<form.Textarea @label='Comment' @name='comment' required />
<Button type='submit'>Submit</Button>
</ToucanForm>
```
```js component
import Component from …
```

feat: Add Input support to toucan-form

---

docs/toucan-form/changeset-validation/demo/base-demo.md
docs/toucan-form/native-validation/demo/base-demo.md
packages/ember-toucan-form/src/-private/checkbox-field.hbs
packages/ember-toucan-form/src/-private/checkbox-field.ts
packages/ember-toucan-form/src/components/toucan-form.hbs
packages/ember-toucan-form/src/components/toucan-form.ts
test-app/tests/integration/components/toucan-form/toucan-form-test.gts

Downstream of https://github.com/CrowdStrike/ember-toucan-core/pull/134
Adds checkbox support to Toucan Form.
---
- Visit https://0c35392f.ember-toucan-core.pages.dev/docs/toucan-form/native-validation
- Click submit
- Verify the checkbox element has an error message
- Check the checkbox
- Verify the checkbox error goes away
- Fill out the form and submit it, verify the submitted data has `true` set for `terms`
---
https://user-images.githubusercontent.com/8069555/232543282-9fe325e3-def2-4fe5-bcdf-30c8cfa733e0.mov

toucan-form: Add Checkbox support

---

docs/toucan-form/changeset-validation/demo/base-demo.md
docs/toucan-form/native-validation/demo/base-demo.md
packages/ember-toucan-core/src/components/form/fields/checkbox-group.hbs
packages/ember-toucan-core/src/components/form/fields/checkbox-group.ts
packages/ember-toucan-core/src/components/form/fields/radio-group.hbs
packages/ember-toucan-form/src/-private/radio-group-field.hbs
packages/ember-toucan-form/src/-private/radio-group-field.ts
packages/ember-toucan-form/src/components/toucan-form.hbs
packages/ember-toucan-form/src/components/toucan-form.ts
test-app/tests/integration/components/toucan-form/toucan-form-test.gts

Downstream of https://github.com/CrowdStrike/ember-toucan-core/pull/135
Adds RadioGroup support to Toucan Form.  Usage is:
```hbs template
<ToucanForm
class='space-y-4 max-w-xs'
@data={{changeset this.data this.validations}}
@dataMode='mutable'
@onSubmit={{this.handleSubmit}}
@validate={{validate-changeset}}
as |form|
>
<form.RadioGroup @label='Radios' @name='radio' as |group|>
<group.RadioField @label='option-1' @value='option-1' data-radio-1 />
<group.RadioField @label='option-2' @value='option-2' data-radio-2 />
</form.RadioGroup>
<Button type='submit'>Submit</Button>
</ToucanForm>
```
```js component
import Component from '@glimmer/component';
import { action } from '@ember/object';
import {
validatePresence,
validateFormat,
} from 'ember-changeset-validations/validators';
export …
```

toucan-form: Add RadioGroup support 

---

.changeset/fuzzy-lies-jump.md
packages/ember-toucan-core/src/-private/components/error.hbs
packages/ember-toucan-core/src/components/form/controls/checkbox.hbs
packages/ember-toucan-core/src/components/form/fields/file-input.hbs
packages/ember-toucan-core/src/components/form/file-input/delete-button.hbs

This PR replaces the placeholder icons with Toucan icons.
Closes #49 
---
- Visit https://8d11545e.ember-toucan-core.pages.dev/docs/components/checkbox-field
- Check the checkbox and view the new checkmark
- Go to https://8d11545e.ember-toucan-core.pages.dev/docs/components/checkbox-field#checkboxfield-with-isindeterminate and view the indeterminate icon
- Visit https://8d11545e.ember-toucan-core.pages.dev/docs/components/file-input-field
- View the new upload icon
- View the new trash icon
- Visit https://8d11545e.ember-toucan-core.pages.dev/docs/components/textarea-field#textareafield-with-label-and-error
- View the new error icon
---
| BEFORE  | AFTER |
| <img width="336" alt="Screenshot 2023-04-20 at 11 57 36 AM" …

Replace icons with Toucan Icons

---

.changeset/long-months-leave.md
packages/ember-toucan-form/src/-private/checkbox-field.hbs
packages/ember-toucan-form/src/-private/checkbox-group-field.hbs
packages/ember-toucan-form/src/-private/input-field.hbs
packages/ember-toucan-form/src/-private/radio-group-field.hbs
packages/ember-toucan-form/src/-private/textarea-field.hbs
test-app/tests/integration/components/toucan-form/form-checkbox-group-test.gts
test-app/tests/integration/components/toucan-form/form-checkbox-test.gts
test-app/tests/integration/components/toucan-form/form-input-test.gts
test-app/tests/integration/components/toucan-form/form-radio-group-test.gts
test-app/tests/integration/components/toucan-form/form-textarea-test.gts

This PR adds read only support to all form elements.  https://github.com/CrowdStrike/ember-toucan-core/pull/132 added `@isReadOnly` to core, so this exposes `@isReadOnly` when using these components in toucan-form.
---
- Integration tests cover the new functionality, so no new features or anything. Only Component API changes!
---
N/A

toucan-form: Add readonly support

---

packages/ember-toucan-form/src/-private/textarea-field.hbs
packages/ember-toucan-form/src/-private/textarea-field.ts
test-app/tests/integration/components/toucan-form/form-textarea-test.gts

This PR attempts to expose all named blocks from textarea within toucan-form.  This is more of a conversation PR to see if we want to go with this approach due to the limitations with named blocks.
Depending on how this goes, I'll update all the other components as well (maybe via a feature branch for smaller PRs).
---
- Green Build
---
M/A

toucan-form: Expose named blocks for textarea

---

packages/ember-toucan-form/src/-private/input-field.hbs
packages/ember-toucan-form/src/-private/input-field.ts
test-app/tests/integration/components/toucan-form/form-input-test.gts

**NOTE:** This is going into the `feature-toucan-form-named-blocks` feature branch.  Once everything is feature complete, that branch will be put up for PR to merge into `main` with a changeset.  I'm making separate PRs for these so it's a bit easier to review on a component-by-component basis.
This PR adds named-block support to `form.Input`.
---
- Green build
- We test the named blocks via integration tests
---
N/A - this is exposing functionality of `toucan-form` already in `toucan-core`

toucan-form: Input named block support

---

CONTRIBUTING.md
local-setup.bash

Updating the docs with new instructions related to using `turbo`:
```
./local-setup.bash
```
Please follow the instructions (locally) in the contributing doc and confirm that it works for you 👍 .
---
N / A

docs: Update contributing docs and add bash script

---

packages/ember-toucan-form/src/-private/checkbox-field.hbs
packages/ember-toucan-form/src/-private/checkbox-field.ts
test-app/tests/integration/components/toucan-form/form-checkbox-test.gts

**NOTE:** This is going into the `feature-toucan-form-named-blocks` feature branch.  Once everything is feature complete, that branch will be put up for PR to merge into `main` with a changeset.  I'm making separate PRs for these so it's a bit easier to review on a component-by-component basis.
Downstream of https://github.com/CrowdStrike/ember-toucan-core/pull/150
---
This PR adds named-block support to `form.Checkbox`.
---
- Green build
- We test the named blocks via integration tests
---
N/A - this is exposing functionality of `toucan-form` already in `toucan-core`

toucan-form: Checkbox named block support

---

packages/ember-toucan-form/src/-private/checkbox-group-field.hbs
packages/ember-toucan-form/src/-private/checkbox-group-field.ts
test-app/tests/integration/components/toucan-form/form-checkbox-group-test.gts

**NOTE:** This is going into the `feature-toucan-form-named-blocks` feature branch.  Once everything is feature complete, that branch will be put up for PR to merge into `main` with a changeset.  I'm making separate PRs for these so it's a bit easier to review on a component-by-component basis.
Downstream of https://github.com/CrowdStrike/ember-toucan-core/pull/150
---
This PR adds named-block support to `form.CheckboxGroup`.
---
- Green build
- We test the named blocks via integration tests
---
N/A - this is exposing functionality of `toucan-form` already in `toucan-core`

toucan-form: CheckboxGroup named block support

---

CONTRIBUTING.md

Removes a duplicate `Option #1` in the contributing docs.

docs: Remove duplicate option 1 in contributing

---

.changeset/lazy-items-shake.md
docs/components/textarea-field/index.md
packages/ember-toucan-core/src/components/form/fields/textarea.hbs
packages/ember-toucan-core/src/components/form/fields/textarea.ts
test-app/tests/integration/components/textarea-field-test.gts

Added character count functionality to the TextArea field
[Link to textarea field docs](https://1e827f8c.ember-toucan-core.pages.dev/docs/components/textarea-field)
1. Scroll down to UI states
2. Type text into the "character block" UI examples.

feat: Add character count to TextArea Field component

---

.changeset/young-houses-help.md
docs-app/package.json
packages/ember-toucan-form/package.json
pnpm-lock.yaml
test-app/config/ember-try.js
test-app/package.json

Updates to the [latest version](https://github.com/CrowdStrike/ember-headless-form/releases/tag/ember-headless-form%401.0.0-beta.2) of `ember-headless-form`.
---
- Green build
---
N/A

chore: Update ember-headless-form dependency

---

docs-app/.template-lintrc.js
docs-app/package.json
packages/ember-toucan-core/package.json
packages/ember-toucan-form/package.json
pnpm-lock.yaml
test-app/.template-lintrc.js
test-app/package.json

This PR upgrades `ember-template-lint` [to the latest](https://github.com/ember-template-lint/ember-template-lint/releases/tag/v5.8.0) which has a [bug fix](https://github.com/ember-template-lint/ember-template-lint/pull/2891) from @NullVoxPopuli that allows us to remove some overrides
---
- Green build - only affects CI
---
N/A

chore: Upgrade ember-template-lint

---

docs-app/package.json
pnpm-lock.yaml

We don't need this, as we are already on an Ember version that supports `@cached` natively (>= 4.1).
This will also fix running into https://github.com/CrowdStrike/ember-headless-form/issues/146 for the docs-app.

chore: remove unused ember-cached-decorator-polyfill

---

.github/actions/pnpm/action.yml
package.json

The `engines` field of `package.json` is supported by PNPM and is thus version-manager independent. PNPM will fail if its version is out of range. See my [code comment](https://github.com/CrowdStrike/ember-toucan-core/pull/175/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R15) for why we should support a specific range.
Volta, meanwhile, is our preferred version manager. It will look to the `volta` field of `package.json` to determine which Node.js and PNPM versions to use. 
> Note that Volta's PNPM support is [experimental](https://docs.volta.sh/advanced/pnpm) and requires the environmental variable `VOLTA_FEATURE_PNPM` to be set to `1`.
We should probably upgrade to a version 6.1 lock file and PNPM 8 as well, though I considered it out of scope. Happy to …

chore: Add engines and volta fields to package.json

---

CONTRIBUTING.md

- Uppercase proper nouns ("bash" → "Bash")
- Use brand formatting ("VSCode" → "VS Code")
- Use backticks consistently—only when referring to code, binaries, directories ("the `test-app`" → "the test-app", "the docs-app directory" → "the `docs-app` directory")
- Add newlines after same-paragraph sentences for easier editing
- Link all URLs
- Other small changes for speed, clarity, correctness

fix: Minor CONTRIBUTING.md improvements

---

.changeset/polite-bobcats-do.md
packages/ember-toucan-core/src/components/form/controls/checkbox.hbs
packages/ember-toucan-core/src/components/form/controls/checkbox.ts
packages/ember-toucan-core/src/components/form/fields/checkbox.hbs
packages/ember-toucan-core/src/components/form/fields/checkbox.ts
test-app/tests/integration/components/checkbox-test.gts

This is a small but breaking change that removes `value` as an attribute in favor of `@value` the argument.  The reason for the change is consistency. Other controls that accept a value accept it by a `@value` argument.
---
1. Navigate to the Checkbox Group Field at the preview URL.
2. Use your browser's inspector to inspect the `<input />` of one of the checkboxes. Note the value of its `value` property.
4. Confirm that value is equal to the `@value` specified in the demo template below it.

chore: add @value support to Form::Controls::Checkbox

---

docs-app/package.json
docs-app/tests/acceptance/button-test.gts
packages/ember-toucan-core/package.json
packages/ember-toucan-form/package.json
pnpm-lock.yaml
test-app/package.json
test-app/tests/integration/components/checkbox-field-test.gts
test-app/tests/integration/components/checkbox-group-field-test.gts
test-app/tests/integration/components/checkbox-test.gts
test-app/tests/integration/components/field-test.gts
test-app/tests/integration/components/file-input-field-test.gts
test-app/tests/integration/components/file-input-test.gts
test-app/tests/integration/components/form/file-input/delete-button-test.gts
test-app/tests/integration/components/form/file-input/list-item-test.gts
test-app/tests/integration/components/form/file-input/list-test.gts
test-app/tests/integration/components/input-field-test.gts
test-app/tests/integration/components/input-test.gts
test-app/tests/integration/components/radio-field-test.gts
test-app/tests/integration/components/radio-group-field-test.gts
test-app/tests/integration/components/radio-test.gts
test-app/tests/integration/components/textarea-field-test.gts
test-app/tests/integration/components/textarea-test.gts
test-app/tests/integration/components/toucan-form/form-checkbox-group-test.gts
test-app/tests/integration/components/toucan-form/form-checkbox-test.gts
test-app/tests/integration/components/toucan-form/form-input-test.gts
test-app/tests/integration/components/toucan-form/form-radio-group-test.gts
test-app/tests/integration/components/toucan-form/form-textarea-test.gts
test-app/tests/integration/components/toucan-form/toucan-form-test.gts

This PR upgrades us to the latest `eslint-plugin-ember` and removes the `eslint-disable` comments in our `gts` files.  Fixed via:
- https://github.com/ember-cli/eslint-plugin-ember/issues/1750
- https://github.com/ember-cli/eslint-plugin-ember/pull/1853
With this change, you can now click the lightbulb in VS Code > Auto-fix all issues.  Or via the CLI you can do `pnpm lint:js:fix` to resolve all eslint issues automatically.
Closes #43 
---
- Green build
---
N/A

#43: Upgrade to latest eslint-plugin-ember, remove eslint-disable, and make --fix work again 

---

.changeset/nine-taxis-drop.md
docs/toucan-form/changeset-validation/demo/base-demo.md
packages/ember-toucan-core/src/components/form/controls/file-input.hbs
packages/ember-toucan-core/src/components/form/fields/file-input.ts
packages/ember-toucan-form/src/-private/file-input-field.hbs
packages/ember-toucan-form/src/-private/file-input-field.ts
packages/ember-toucan-form/src/components/toucan-form.hbs
packages/ember-toucan-form/src/components/toucan-form.ts
test-app/tests/integration/components/file-input-test.gts
test-app/tests/integration/components/toucan-form/form-file-input-test.gts
test-app/tests/integration/components/toucan-form/toucan-form-test.gts

This PR adds `form.FileInput` support to `toucan-form`.
```hbs
<ToucanForm
@data={{changeset this.data this.validations}}
@onSubmit={{this.handleSubmit}}
@validate={{(validate-changeset)}}
as |form|
>
<form.FileInput
@label='Files to attach'
@trigger='Select files'
@deleteLabel='Delete'
@name='files'
/>
<Button type='submit'>Submit</Button>
</ToucanForm>
```
---
- Green build
- Go to https://e6846db9.ember-toucan-core.pages.dev/docs/toucan-form/changeset-validation
- Click submit button
- Verify error is displayed under FileInput component
- Click Select files button
- Add a file
- Verify error goes away
- Complete the rest of the form
- Submit it
- Verify in the alert `files` has content
---
https://github.com/CrowdStrike/ember-toucan-core/assets/8069555/200e10f4-fbec-4c9c-95d5-7e09b65849 …

Add FileInput support to toucan-form

---

.github/workflows/ci.yml

Testing for newer versions of typescript. 
CI should be ✅ 
---
N/A

fix: Update typescript version tests to include 5.0 and 5.1

---

.changeset/fluffy-cameras-drum.md
docs/components/checkbox-field/index.md
docs/components/checkbox-group-field/index.md
docs/components/file-input-field/index.md
docs/components/input-field/index.md
docs/components/radio-field/index.md
docs/components/radio-group-field/index.md
docs/components/textarea-field/index.md
packages/ember-toucan-core/src/-private/components/lock-icon.hbs
packages/ember-toucan-core/src/-private/components/lock-icon.ts
packages/ember-toucan-core/src/components/form/fields/checkbox-group.hbs
packages/ember-toucan-core/src/components/form/fields/checkbox-group.ts
packages/ember-toucan-core/src/components/form/fields/checkbox.hbs
packages/ember-toucan-core/src/components/form/fields/checkbox.ts
packages/ember-toucan-core/src/components/form/fields/file-input.hbs
packages/ember-toucan-core/src/components/form/fields/file-input.ts
packages/ember-toucan-core/src/components/form/fields/input.hbs
packages/ember-toucan-core/src/components/form/fields/input.ts
packages/ember-toucan-core/src/components/form/fields/radio-group.hbs
packages/ember-toucan-core/src/components/form/fields/radio-group.ts
packages/ember-toucan-core/src/components/form/fields/textarea.hbs
packages/ember-toucan-core/src/components/form/fields/textarea.ts
test-app/tests/integration/components/checkbox-field-test.gts
test-app/tests/integration/components/checkbox-group-field-test.gts
test-app/tests/integration/components/file-input-field-test.gts
test-app/tests/integration/components/input-field-test.gts
test-app/tests/integration/components/radio-group-field-test.gts
test-app/tests/integration/components/textarea-field-test.gts

This PR adds the lock icon for disabled and readonly states according to our designs.
---
- Visit https://844e929c.ember-toucan-core.pages.dev/docs/components/checkbox-group-field and the following components
- checkbox-field
- checkbox-group-field
- file-input-field
- input-field
- radio-group-field
- textarea-field
- Scroll down to the "All UI States" section(s)
- Verify the lock icon appears for both disabled and readonly states
---
While I was in here, I adjusted some of the iconography in our demos to be a bit closer to what we'd prefer.
| BEFORE  | AFTER |
| <img width="416" alt="Screenshot 2023-06-20 at 7 56 19 PM" src="https://github.com/CrowdStrike/ember-toucan-core/assets/8069555/269b0285-450d-4486-89f1-48192992a23f">  | <img width="400" …

Add lock icon for disabled and readonly states

---

.changeset/pretty-cheetahs-burn.md
packages/ember-toucan-core/src/-private/components/hint.hbs
packages/ember-toucan-core/src/-private/components/hint.ts
packages/ember-toucan-core/src/-private/components/label.hbs
packages/ember-toucan-core/src/-private/components/label.ts
packages/ember-toucan-core/src/components/form/fields/checkbox-group.hbs
packages/ember-toucan-core/src/components/form/fields/checkbox.hbs
packages/ember-toucan-core/src/components/form/fields/file-input.hbs
packages/ember-toucan-core/src/components/form/fields/input.hbs
packages/ember-toucan-core/src/components/form/fields/radio-group.hbs
packages/ember-toucan-core/src/components/form/fields/radio.hbs
packages/ember-toucan-core/src/components/form/fields/textarea.hbs
test-app/tests/integration/components/checkbox-field-test.gts
test-app/tests/integration/components/checkbox-group-field-test.gts
test-app/tests/integration/components/file-input-field-test.gts
test-app/tests/integration/components/input-field-test.gts
test-app/tests/integration/components/radio-field-test.gts
test-app/tests/integration/components/radio-group-field-test.gts
test-app/tests/integration/components/textarea-field-test.gts

(Downstream of https://github.com/CrowdStrike/ember-toucan-core/pull/193 for DX improvement reasons)
Adds disabled styling to labels and hint blocks when `@isDisabled`.
---
View the following URLs and verify `text-disabled` is applied
- https://ceb26a4d.ember-toucan-core.pages.dev/docs/components/textarea-field#textareafield-with-label-and-isdisabled
- https://ceb26a4d.ember-toucan-core.pages.dev/docs/components/radio-group-field#radiogroupfield-with-label-and-isdisabled
- https://ceb26a4d.ember-toucan-core.pages.dev/docs/components/radio-field#radiofield-with-label-hint-and-value-isdisabled
- https://ceb26a4d.ember-toucan-core.pages.dev/docs/components/input-field#inputfield-with-label-and-isdisabled
- https://ceb26a4d.ember-toucan-core.pages.dev/docs/components/file-input-field#fileinput …

Fix: Apply text-disabled to labels and hint blocks when components are disabled

---

.changeset/eleven-crabs-type.md
docs/components/file-input-field/demo/base-demo.md
docs/components/file-input-field/index.md
packages/ember-toucan-core/src/components/form/fields/file-input.hbs
packages/ember-toucan-core/src/components/form/file-input/delete-button.hbs
packages/ember-toucan-core/src/components/form/file-input/list-item.hbs
packages/ember-toucan-core/src/components/form/file-input/list.hbs
test-app/tests/integration/components/file-input-field-test.gts

This gets our `file-input` component closer in line with what the designs call for.
- Made `file-input` full-width after talking with Mary
- Updated disabled styling
- Moved the lock icon inside of the button after talking with Mary and David
- Adjusted list item padding and button styling
Closes #86 
---
- Visit https://08fedf99.ember-toucan-core.pages.dev/docs/components/file-input-field
- Verify it matches the Figma file
---
**Disabled styling now matches Figma**
**Width is now set to full**
**Hover + Focus states on delete button**

Update file-input styling with latest designs

---

.changeset/cyan-dots-speak.md
packages/ember-toucan-core/src/components/form/controls/character-count.hbs
packages/ember-toucan-core/src/components/form/controls/character-count.ts
test-app/tests/integration/components/character-count-test.gts

This adds styling as requested by design when the current character length is greater than the maximum.
---
- Go to https://a9a80cf2.ember-toucan-core.pages.dev/docs/components/textarea-field#textareafield-with-character-count-with-a-single-error
- Type over the maximum characters
- Verify the character count text turns red
- Now do the same thing with https://a9a80cf2.ember-toucan-core.pages.dev/docs/components/input-field#inputfield-with-character-count-with-single-error
---
https://github.com/CrowdStrike/ember-toucan-core/assets/8069555/628139b8-284c-4149-ac73-55dc6f8410ce
https://github.com/CrowdStrike/ember-toucan-core/assets/8069555/8769739f-bc31-4607-b0c6-0881be36e8ab

Style character counter when current is greater than max

---

.changeset/curly-pants-yawn.md
packages/ember-toucan-core/src/components/button.hbs

If the button is the child of a flex parent then,
when disabled, the yielded content wrapping span
needs a flex-grow CSS property to ensure that the
label can expand, and push the button width out
to fill the full width of the parent
---
---

fix: button flex grow

---

docs/components/autocomplete/index.md
docs/components/checkbox/index.md
docs/components/input/index.md
docs/components/radio/index.md
docs/components/textarea/index.md

This addresses some PR feedback from @nicolechung on a previous PR, where we link to the Field components from the Controls.
---
- Green build
---
N/A

docs: Link to fields from control docs

---

.changeset/spicy-suits-pay.md
docs/toucan-form/changeset-validation/demo/base-demo.md
packages/ember-toucan-core/src/template-registry.ts
packages/ember-toucan-form/src/-private/multiselect-field.hbs
packages/ember-toucan-form/src/-private/multiselect-field.ts
packages/ember-toucan-form/src/components/toucan-form.hbs
packages/ember-toucan-form/src/components/toucan-form.ts
test-app/tests/integration/components/toucan-form/form-multiselect-test.gts
test-app/tests/integration/components/toucan-form/toucan-form-test.gts

This PR exposes `form.Multiselect` from `ToucanForm`.
---
- Green build
- Visit https://baf6a022.ember-toucan-core.pages.dev/docs/toucan-form/changeset-validation
- Click submit
- Verify an error is displayed for the multi select
- Select an option and then blur the input
- Verify the error is removed
---

Add form.Multiselect support to ToucanForm component

---

.changeset/smart-mice-crash.md
.changeset/twelve-gifts-camp.md
docs/components/autocomplete-field/demo/base-demo.md
docs/components/autocomplete/demo/base-demo.md
docs/components/autocomplete/index.md
docs/toucan-form/changeset-validation/demo/base-demo.md
packages/ember-toucan-core/src/components/form/controls/autocomplete.hbs
packages/ember-toucan-core/src/components/form/controls/autocomplete.ts
packages/ember-toucan-core/src/components/form/fields/autocomplete.hbs
packages/ember-toucan-core/src/components/form/fields/autocomplete.ts
packages/ember-toucan-form/src/-private/autocomplete-field.hbs
packages/ember-toucan-form/src/-private/autocomplete-field.ts
test-app/tests/integration/components/autocomplete-test.gts

The consumer is currently allowed to pass either an array of strings _or_ an array of objects. @ynotdraw and I talked about it. We think removing support for arrays of objects makes for an overall better component. 
This change does move some work to the consumer. If the consumer's data structure is anything other than an array of strings, the consumer will now have to do a lookup after `@onChange(selected: string)` is called to find the selected object in the `@options` array. Consumers will also have to map their data to our `string[]` structure, though this is easily done.
Despite this additional work for the consumer, we think that the **disadvantages** of supporting an array of objects make this change worthwhile:
Various [conditionals](https://github.com/CrowdStrike/ember-toucan-core …

chore: Autocomplete tweaks

---

docs-app/package.json
packages/ember-toucan-core/package.json
packages/ember-toucan-form/package.json
pnpm-lock.yaml
test-app/package.json

This PR removes some peer dependency warnings from `pnpm` when running an install.  This gets rid of a big chunk of them; however, we still get the following:
```bash
docs-app
├─┬ ember-cli-dependency-checker 3.3.1
│ └── ✕ unmet peer ember-cli@"^3.2.0 || ^4.0.0": found 5.1.0
├─┬ @crowdstrike/ember-oss-docs 1.1.6
│ ├── ✕ unmet peer @docfy/core@^0.5.0: found 0.6.0
│ └── ✕ unmet peer @docfy/ember@^0.5.0: found 0.6.0
└─┬ @crowdstrike/ember-toucan-core 0.2.2
└─┬ ember-velcro 2.1.0
└─┬ ember-functions-as-helper-polyfill 2.1.1
└── ✕ unmet peer ember-source@"^3.25.0 || ^4.0.0": found 5.1.0
packages/ember-toucan-core
├─┬ rollup-plugin-ts 3.2.0
│ └─┬ ts-clone-node 2.0.4
│   └── ✕ unmet peer typescript@"^3.x || ^4.x": found 5.0.2
└─┬ ember-velcro 2.1.0
└─┬ ember-functions-as-helper-polyfill 2.1.1 …
```

Dependency Housekeeping

---

docs/components/autocomplete/index.md
docs/components/multiselect-field/demo/base-demo.md
docs/components/multiselect-field/index.md
docs/components/multiselect/demo/base-demo.md
docs/components/multiselect/index.md
docs/toucan-form/changeset-validation/demo/base-demo.md
packages/ember-toucan-core/src/components/form/controls/multiselect.hbs
packages/ember-toucan-core/src/components/form/controls/multiselect.ts
packages/ember-toucan-core/src/components/form/fields/multiselect.hbs
packages/ember-toucan-core/src/components/form/fields/multiselect.ts
packages/ember-toucan-form/src/-private/autocomplete-field.ts
packages/ember-toucan-form/src/-private/multiselect-field.hbs
packages/ember-toucan-form/src/-private/multiselect-field.ts
test-app/tests/integration/components/multiselect-test.gts

The consumer is currently allowed to pass either an array of strings _or_ an array of objects. @ynotdraw and I talked about it. We think removing support for arrays of objects makes for an overall better component. 
This change does move some work to the consumer. If the consumer's data structure is anything other than an array of strings, the consumer will now have to do a lookup after `@onChange(selected: string[])` is called to find the selected object in the `@options` array. Consumers will also have to map their data to our `string[]` structure, though this is easily done.
Despite this additional work for the consumer, we think that the **disadvantages** of supporting an array of objects make this change worthwhile:
Various [conditionals](https://github.com/CrowdStrike/ember-toucan-co …

chore: Multiselect tweaks

---

.changeset/hip-bulldogs-kick.md
docs/components/autocomplete-field/demo/base-demo.md
docs/components/checkbox-group-field/demo/base-demo.md
docs/components/file-input-field/demo/base-demo.md
docs/components/input-field/demo/base-demo.md
docs/components/multiselect-field/demo/base-demo.md
docs/components/radio-field/demo/base-demo.md
docs/components/radio-group-field/demo/base-demo.md
docs/components/textarea-field/demo/base-demo.md
docs/toucan-form/changeset-validation/demo/base-demo.md
packages/ember-toucan-core/src/components/form/controls/autocomplete.hbs
packages/ember-toucan-core/src/components/form/controls/multiselect.hbs
packages/ember-toucan-core/src/components/form/fields/input.hbs
packages/ember-toucan-core/src/components/form/fields/textarea.hbs

- Adds `w-full` to all form elements
- Went ahead and made this a breaking change (aka pre-1.0 `minor` update) to play it safe
- Adjusts the changeset demo to include character counter examples with maximum lengths
- Adjusts the changeset demo to be visually centered
---
- View doc pages and verify everything looks good, or view the images below
---
https://github.com/CrowdStrike/ember-toucan-core/assets/8069555/3c66eb59-1e97-4037-975b-debb1f975436

Set all form elements to `w-full` and adjust docs

---

.changeset/bright-spies-share.md
.changeset/spicy-suits-pay.md
.changeset/warm-planes-fix.md
docs/components/multiselect-field/demo/base-demo.md
docs/components/multiselect-field/index.md
docs/components/multiselect/demo/base-demo.md
docs/components/multiselect/index.md
docs/toucan-form/changeset-validation/demo/base-demo.md
packages/ember-toucan-core/src/-private/components/form/controls/multiselect/chip.hbs
packages/ember-toucan-core/src/-private/components/form/controls/multiselect/chip.ts
packages/ember-toucan-core/src/-private/components/form/controls/multiselect/remove.hbs
packages/ember-toucan-core/src/-private/components/form/controls/multiselect/remove.ts
packages/ember-toucan-core/src/components/form/controls/multiselect.hbs
packages/ember-toucan-core/src/components/form/controls/multiselect.ts
packages/ember-toucan-core/src/components/form/fields/multiselect.hbs
packages/ember-toucan-core/src/components/form/fields/multiselect.ts
packages/ember-toucan-form/src/-private/multiselect-field.hbs
test-app/tests/integration/components/multiselect-field-test.gts
test-app/tests/integration/components/multiselect-test.gts
test-app/tests/integration/components/toucan-form/form-multiselect-test.gts
test-app/tests/integration/components/toucan-form/toucan-form-test.gts

This PR removes the `:remove` named block in favor of a `:chip` named block.  This new block gives us more flexibility for new use cases and allows for the following:
- Exposes the `Chip` component directly to consumers
- Attributes to be spread onto the underlying `Chip` component
- Allows consumers to wrap the chip contents in whatever component they need.  For example, if they want to truncate the text of a long select option, they can do `<TruncateText>{{chip.option}}</TruncateText>` and we don't need to support it internally
---
- Green build
---
- No visual changes, only component API changes

Remove the :remove named block and yield a :chip block instead

---

.changeset/kind-ways-fold.md
docs/components/multiselect-field/demo/base-demo.md
docs/components/multiselect-field/index.md
docs/components/multiselect/demo/base-demo.md
docs/components/multiselect/index.md
docs/toucan-form/changeset-validation/demo/base-demo.md
packages/ember-toucan-core/src/components/form/controls/autocomplete.ts
packages/ember-toucan-core/src/components/form/controls/multiselect.hbs
packages/ember-toucan-core/src/components/form/controls/multiselect.ts
packages/ember-toucan-core/src/components/form/fields/autocomplete.ts
packages/ember-toucan-core/src/components/form/fields/multiselect.hbs
packages/ember-toucan-core/src/components/form/fields/multiselect.ts
packages/ember-toucan-form/src/-private/multiselect-field.hbs
test-app/tests/integration/components/multiselect-field-test.gts
test-app/tests/integration/components/multiselect-test.gts
test-app/tests/integration/components/toucan-form/form-multiselect-test.gts
test-app/tests/integration/components/toucan-form/toucan-form-test.gts

We want to increase consistency where we can. In the case of what's displayed when there are no results, we (@clintcs, @ynotdraw)—after some discussion—_think_ we can get away with being prescriptive and forgo a named block (`:noResults`) in favor of an argument (`@noResultsText`). This will also bring Multiselect in line with Autocomplete, which also supports `@noResultsText`.
1. Navigate to the [preview URL](https://8a5dc82c.ember-toucan-core.pages.dev/docs/components/multiselect).
1. Filter a demo until there are no results.
1. Verify that "No results" is shown in the popover.

chore: add `@noResultsText` argument to Multiselect

---

packages/ember-toucan-core/src/components/form/controls/autocomplete.hbs
packages/ember-toucan-core/src/components/form/controls/multiselect.hbs

It's very subtle and I notice it more on my 5k monitor - the chevron color on the autocomplete and multiselect were not the same.  This PR adds an explicit class so that they are identical.
---
- Verify the colors for the chevrons on the changeset demo are the same
---
Once again, kind of hard to tell, but the bottom chevron (multiselect) is _slightly_ lighter than the top one (autocomplete) due to the classes on the containers since the SVG has `fill="currentColor"`.
| BEFORE  | AFTER |
| <img width="138" alt="Screenshot 2023-07-27 at 12 52 34 PM" src="https://github.com/CrowdStrike/ember-toucan-core/assets/8069555/df29f132-72c8-4374-8420-4452dbfce5fa">  | <img width="109" alt="Screenshot 2023-07-27 at 12 53 02 PM" …

Fix chevron colors in autocomplete/multiselect

---

.changeset/tough-planets-raise.md
docs/components/autocomplete-field/index.md
docs/components/autocomplete/index.md
docs/components/multiselect-field/index.md
docs/components/multiselect/index.md
packages/ember-toucan-core/src/components/form/controls/autocomplete.ts
packages/ember-toucan-core/src/components/form/fields/autocomplete.ts
test-app/tests/integration/components/autocomplete-field-test.gts
test-app/tests/integration/components/autocomplete-test.gts
test-app/tests/integration/components/toucan-form/form-autocomplete-test.gts
test-app/tests/integration/components/toucan-form/toucan-form-test.gts

Makes `@noResultsText` required as a followup to [this discussion](https://github.com/CrowdStrike/ember-toucan-core/pull/238#discussion_r1276486527).
- Makes Autocomplete `@noResultsText` required
- Adds "Optional" descriptors to Autocomplete's arguments documentation
- Add "No results text" to Autocomplete Field documentation
- Moves Multiselect's `@noResultsText` documentation to the top because it's required
We're good as long as the build is green.

chore: make Autocomplete `@noResultsText` required

---

.changeset/two-pets-travel.md
docs/components/multiselect-field/index.md
docs/components/multiselect/demo/base-demo.md
docs/components/multiselect/index.md
packages/ember-toucan-core/src/-private/components/form/controls/multiselect/select-all.hbs
packages/ember-toucan-core/src/-private/components/form/controls/multiselect/select-all.ts
packages/ember-toucan-core/src/components/form/controls/multiselect.hbs
packages/ember-toucan-core/src/components/form/controls/multiselect.ts
packages/ember-toucan-core/src/components/form/fields/multiselect.hbs
packages/ember-toucan-core/src/components/form/fields/multiselect.ts
packages/ember-toucan-form/src/-private/multiselect-field.hbs
test-app/tests/integration/components/multiselect-field-test.gts
test-app/tests/integration/components/multiselect-test.gts
test-app/tests/integration/components/toucan-form/form-multiselect-test.gts

Adds "Select all" functionality to multiselect.
---
- Visit https://8b4676f3.ember-toucan-core.pages.dev/docs/components/multiselect
- For this section, use the bottom multiselect ( "With Select All" )
**Select all states**
- Click the multiselect
- Click "Select all"
- Verify the checkbox is checked
- Verify all items in the popover are also checked
- Click "Orange"
- Verify "Orange" is removed from the list
- Verify the "Select all" checkbox is now in the indeterminate state
- Click "Select all" again
- Verify all items are selected again and "Orange", in particular, is re-added
- Click "Select all" again
- Verify all items are unselected
- Verify the "Select all" checkbox is unchecked
**Filtering**
- Click the multiselect
- Type into the multiselect to trigger filtering.  For example …

Add "Select all" functionality to multiselect

---

.changeset/heavy-clocks-collect.md
README.md
packages/ember-toucan-core/src/-private/components/form/controls/autocomplete/option.gts
packages/ember-toucan-core/src/components/form/controls/autocomplete.gts
packages/ember-toucan-core/src/test-support/components/autocomplete.ts
packages/ember-toucan-core/src/test-support/components/button.ts
packages/ember-toucan-core/src/test-support/index.ts
test-app/tests/integration/components/autocomplete-field-test.gts
test-app/tests/integration/components/autocomplete-test.gts
test-app/tests/integration/components/button-test.gts

- Adds Autocomplete test helpers
- Reworks the Autocomplete tests to use the new test helpers
---
We're good if the build is green.

Add Autocomplete test helpers

---

test-app/tests/integration/components/toucan-form/toucan-form-test.gts

I [recently added](https://github.com/CrowdStrike/ember-toucan-core/pull/248/files#diff-6223e65e62fecec914eebf1ba0fe94840dfb2f8cefa9e1367ff8fbaf7f9432e6R471) a `data-autocomplete` attribute to the top level of Autocomplete to facilitate element selection in test helpers. 
Turns out `data-autocomplete` was [being](https://github.com/CrowdStrike/ember-toucan-core/pull/256/files#diff-c9cf70efb682ced097e7d0302945a584b4346e52646f78b96ee34fb38d5dd2a1L199) [used](https://github.com/CrowdStrike/ember-toucan-core/pull/256/files#diff-c9cf70efb682ced097e7d0302945a584b4346e52646f78b96ee34fb38d5dd2a1L257) in one of our form tests. Because Autocomplete's top-level `data-autocomplete` comes first in the DOM, the form test was selecting it instead of Autocomplete's `<input />`, causing its tests to fail. …

fix: fix failing Autocomplete tests

---

.changeset/olive-buttons-kiss.md
docs/components/input/demo/base-demo.md
docs/components/textarea/demo/base-demo.md
packages/ember-toucan-core/src/components/form/controls/input.gts
packages/ember-toucan-core/src/components/form/controls/textarea.gts
packages/ember-toucan-core/src/components/form/fields/input.gts
packages/ember-toucan-core/src/components/form/fields/textarea.gts
test-app/tests/integration/components/textarea-field-test.gts
test-app/tests/integration/components/textarea-test.gts

- Adjusts the `input` padding to match the designs
- Adds a container around `textarea` so that the drag handle and long text does not collide with the focus and focus+error shadows.
- **NOTE:** This padding now matches `input` as well (`px-2`). Autocomplete and Multiselect already had these classes specified, so now everything is consistent 🎉 
---
- Visit https://384df54f.ember-toucan-core.pages.dev/docs/components/textarea
- Verify the textarea drag handle has some spacing around it
- Verify the focus shadow does not collide with the content
- Visit https://384df54f.ember-toucan-core.pages.dev/docs/components/textarea-field
- Verify the textarea drag handle has some spacing around it
- Verify the focus shadow does not collide with the content
- Visit …

fix: Add container to textarea to resolve style issues and add padding to input to match

---

.changeset/fluffy-meals-hammer.md
docs/components/autocomplete/index.md
docs/components/multiselect/index.md
packages/ember-toucan-core/src/-private/components/form/controls/multiselect/chip.gts
packages/ember-toucan-core/src/-private/components/form/controls/multiselect/option.gts
packages/ember-toucan-core/src/-private/components/form/controls/multiselect/select-all.gts
packages/ember-toucan-core/src/components/form/controls/multiselect.gts
packages/ember-toucan-core/src/test-support/components/multiselect.ts
packages/ember-toucan-core/src/test-support/index.ts
test-app/tests/integration/components/autocomplete-test.gts
test-app/tests/integration/components/multiselect-field-test.gts
test-app/tests/integration/components/multiselect-test.gts
test-app/tests/integration/components/toucan-form/form-multiselect-test.gts
test-app/tests/integration/components/toucan-form/toucan-form-test.gts

- Adds Multiselect test helpers
- Reworks Multiselect tests to use the new test helpers
---
We're good if the build is green.

Add Multiselect test helpers

---

.github/renovate.json5

By default, we only allow 10 concurrent PRs. If some PRs are red and not trivial to fix, and new updates are only created once a week (see `"schedule": ["after 9pm on sunday"]`), then this can easily lead to a larger backlog, see https://github.com/CrowdStrike/ember-toucan-core/issues/18

Increase renovate's prConcurrentLimit

---

.changeset/afraid-vans-attend.md
packages/ember-toucan-core/src/components/button.gts
test-app/tests/integration/components/button-test.gts

When a type="submit" button has @isDisabled set, it does not prevent submitting the form, because the disabled state (for a11y reasons) does not add the disabled attribute.
Adding an `event.preventDefault()` prevent to send the submit event.
---
Create a form with a submit action and add a `<Button @isDisabled={{true}} type="submit">button</Button>` inside the form and verify that the submit action is not fired when clicking the button.

Add event.preventDefault() when clicking on disabled button

---

.changeset/spotty-lamps-shake.md
packages/ember-toucan-core/src/components/form/controls/textarea.gts
test-app/tests/integration/components/textarea-test.gts

Fixes issue #446 where the underlying `<textarea>` used in `Form::Controls::Textarea` gets out of sync with `@value` changes after typing in the `<textarea>`.
Also adds tests for both current working functionality of updating value before typing in the textarea and the previously broken case of typing in the textarea and then attempting an update of the value from outside the component.
---
Added test cases should cover the functionality changing.
There's no external impact on existing examples to show.
Reversing the change in `textarea.gts` should result in one failed test case for the issue described in #446

fix: set value attribute on textarea instead of in content to ensure value and defaultValue stay in sync with changes

---

.changeset/smooth-scissors-speak.md
packages/ember-toucan-core/src/components/button.gts

min-w-0 adds truncation when used with other components.
---
This should enable truncation when used with other components.
---

style: Button, add truncation

---

.changeset/red-kiwis-eat.md
packages/ember-toucan-core/src/components/form/controls/multiselect.gts
test-app/tests/integration/components/multiselect-test.gts

This PR fixes an issue with multiple multiselect components on the same page. Previously, when clicking on a multiselect container, the code would use `document.querySelector` to find the input element, which could incorrectly target the first multiselect on the page rather than the one that was clicked. 
The fix modifies the `handleContainerClick` method to:
- Accept a MouseEvent parameter
- Use the event's currentTarget to scope the querySelector to the specific container that was clicked
- This ensures each multiselect component correctly focuses its own input when clicked
Added a comprehensive test case that verifies multiple multiselect components work correctly when placed on the same page.
---
1. Add multiple multiselect components to a page
2. Click on each multiselect container …

fix(multiselect): scope chevron clicks to the correct container
